### ISSUE TITLE
Тема курсового

### ISSUE THREAD

**Issue by tshemsedinov** [Maksym1910/TicTacToeApp#1]
Тема курсового `App for Android` не информативна. Нужно, чтобы из темы было понятно, что делает приложение и/или какие навыки программирования проект демонстрирует. Кода пока нет, не могу подсказать, как лучше назвать.

**Comment by Maksym1910** [comment]
Доброго дня ! Деякий код вже є. Хочу написати гру хрестики нолики (
TicTacToe ). З повагою, Рожицький Максим, ІП-93

ср, 27 трав. 2020 о 00:45 Timur Shemsedinov <notifications@github.com> пише:

**Comment by tshemsedinov** [comment]
Код нужно писать прямо в репозитории, делать брэнчи, коммитить в них и потом пул-реквесты в мастер. Чтоб была видна динамика написания кода.

**Comment by Maksym1910** [comment]
Так, зрозумів.
